database:
  dbname: vk
  user: toxic
  password: qwerty123
  host: rc1b-pnfssn9zkznmdbn5.mdb.yandexcloud.net
  port: 6432
  sslmode: verify-full
  target_session_attrs: read-write

api-key:
  key_1: vk1.a.3nkO91uDeCFbgZlQ2RZnjHH7wOilSyJhrAVVlFeKdv3cmTWy4msPdYCJtdaMwMaymqBCwxPPIIImy2rDr91KBIu83CMOubNzyP_VueKUonr4FrB7nLUhk7cFPvDaICL3R5U6yvBKjBoZtEXVKb8NlReWDomxW4fyemTOsFE_EdE6dW2-ZeHFs-bG6k1MghRO50mU9CEUJr5cMhoIHHp69g
  key_2: vk1.a.Q4fwlHwY_-8ounQR9EoxyhNlODFYU3lzAFzeuXHLNxctJvWWB5__lXryu0rGA12Kkae1P0eqdr0W_qJ-PBxSCmuzW7sq3GNaNExq0Hj28rkObt9bwhONN4kQHAV9tlIc1uYqJS3i0bb_zeo1vE_-VsVvZM7b_g1VzoVXGAufTdZvgfvl8o_5yr4mppJ99k9hFInFP3g0lY8OpyZ4nhOg5Q
  key_3: vk1.a.FhlNacZSHE_wH062-BscHFfYocBNESgEff8ZptYPpdhSjpKGyFacGW6B62b3ifsiaHC2dttMd1m__uG4lETbt1P_ZWa1123t7IwRUvHouUmbGEQyOVuDoaV9I_FjpPpg4zE8MJI4ReBIVrz7FvuUHOZfqbbDvFjC0jmMkbWGKLpM2ZRatZtMOgdYL_-tB_0CgSv-8WH5gwZJSIUBCbXOGg
  key_4: vk1.a.LbPxTEsO8rubpf975T8KE9y_cwM_lrbsa_PTqbIpyj0HnhwMfTD16gULUHJtd40-JsmBLl4DCvJtEBZnQvNkwxkzQlpbf7DbrduDUmGNGz5-wFbe9z4DkYM_JCqxEYUhAcHhWkGxyDmhQmi7WdRXO-DYhjwHTlegEWKbbw4K8Y7ilJuFkfPpf36diIdXf2IKi8Opj0al01bNEvrkS-aohw